name: Run Azure Login with OIDC

on:
  push:
    branches: [gh_actions_t1]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Create VM in Azure
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az vm create \
            --resource-group "IT-SPROUT" \
            --location francecentral \
            --name SampleVM \
            --image Ubuntu2204 \
            --size "Standard_B1s" \
            --admin-username azureuser \
            --generate-ssh-keys \
            --verbose

      - name: Extract private key
        run: |
          ls -la ~/.ssh
          echo "========="
          ls -la ~/
          sudo cat ~/.ssh/id_rsa | sudo tee private_key.pem > /dev/null

      - name: Upload private key as artifact
        uses: actions/upload-artifact@v4
        with:
          name: private-key
          path: private_key.pem
